# Copyright (c) 2024 Diagrid Inc.
# Licensed under the MIT License.

name: "Build and testing"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.5
        env:
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
        ports:
          - 2379:2379
    env:
      GOOS: linux
      GOARCH: amd64
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#test
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: 'false'
      - name: Run test
        run: go test
